name: Backend CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List repository files
        run: ls -la

      - name: Setup Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Prepare environment files
        run: |
          echo "DOCKER_CONFIG=docker-compose.yml" > .env
          echo "HOST_UID=$(id -u)" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=db" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=db_name" >> .env
          echo "DB_USERNAME=db_user" >> .env
          echo "DB_PASSWORD=db_password" >> .env
          
          echo "APP_ENV=testing" > .env.testing
          echo "APP_DEBUG=true" >> .env.testing
          echo "DB_CONNECTION=mysql" >> .env.testing
          echo "DB_HOST=test_db" >> .env.testing
          echo "DB_PORT=3306" >> .env.testing
          echo "DB_DATABASE=test_db" >> .env.testing
          echo "DB_USERNAME=test_user" >> .env.testing
          echo "DB_PASSWORD=test_password" >> .env.testing 

      - name: Build containers
        run: make build

      - name: Start services
        run: |
          make up
          # Awaiting OpenSearch ready
          until docker compose exec opensearch curl -s http://localhost:9200/_cluster/health | grep -q '"status":"green" | grep -q '"status":"yellow"'; do
            echo "Waiting for OpenSearch to start..."
            sleep 20
          done

      - name: Wait for test database to be ready
        run: |
          until docker compose exec test_db mysqladmin ping -h"127.0.0.1" -P3306 --silent; do
            echo "Waiting for test database..."
            sleep 5
          done

      - name: Prepare Laravel
        run: |
          docker compose exec app mkdir -p /var/www/html/laravel/storage
          docker compose exec app mkdir -p /var/www/html/laravel/bootstrap/cache
          docker compose exec app chmod -R 775 /var/www/html/laravel/storage
          docker compose exec app chmod -R 775 /var/www/html/laravel/bootstrap/cache

      - name: Install dependencies
        run: make vendor

      - name: Code style check
        run: make cs_check

      - name: Use test environment for Laravel
        run: cp .env.testing laravel/.env

      - name: Run migrations
        run: |
          docker compose exec -w /var/www/html/laravel app php artisan migrate:fresh --seed --force
          docker compose exec -w /var/www/html/laravel app php artisan passport:install --no-interaction

      - name: Run tests
        run: |
          docker compose exec -w /var/www/html/laravel app php artisan test --env=testing

      - name: Stop containers
        if: always()
        run: make down